[workspace]
resolver = "2"

members = [
    "core",
    "domains",
    "domains/photoshy",
    "domains/textshy",
    "whitehat",
    "coordinator",
    "cli",
]

[workspace.package]
version = "0.10.0"
edition = "2021"
license = "Proprietary"
authors = ["StealthEye LLC"]
