[package]
name = "expl"
version = "0.1.0"
edition = "2021"

[dependencies]
obs = { path = "../obs" }
vfy = { path = "../vfy" }
hbr = { path = "../hbr" }
wdn = { path = "../wdn" }
clr = { path = "../clr" }
chk = { path = "../chk" }
